%% policy_transition.m
%
% Gertler (1999) fiscal policy transition dynamics
%
% Initial condition:
% 2014 observed economy
%
% Experiments:
% 1. Government spending
% 2. Social security
% 3. Debt target
%
% Output:
% Counterfactual-Baseline percentage changes
% for k, lambda, r


clear;
clc;


% Load initial state (2014)
data = readtable('initial_states.csv');
state = data(data.year==2014,:);
T = 40; % 40 years


% Government spending experiment
run_dynare_policy(...
    'gertler_policy_g',...
    'gbar',...
    0.20,...
    state,...
    'g_baseline');
run_dynare_policy(...
    'gertler_policy_g',...
    'gbar',...
    0.30,...
    state,...
    'g_counterfactual');


% Social security experiment
run_dynare_policy(...
    'gertler_policy_e',...
    'ebar',...
    0.05,...
    state,...
    'e_baseline');
run_dynare_policy(...
    'gertler_policy_e',...
    'ebar',...
    0.03,...
    state,...
    'e_counterfactual');


% Debt target experiment
run_dynare_policy(...
    'gertler_policy_b',...
    'bbar',...
    0.60,...
    state,...
    'b_baseline');
run_dynare_policy(...
    'gertler_policy_b',...
    'bbar',...
    0.80,...
    state,...
    'b_counterfactual');


% Calculate transition effects
experiments = {
    'g'
    'e'
    'b'
};
output = table();

for i = 1:length(experiments)

    exp = experiments{i};

    % baseline
    load(['temp_' exp '_baseline.mat']);
    base_path = oo_.endo_simul;
    names = cellstr(M_.endo_names);

    % counterfactual
    load(['temp_' exp '_counterfactual.mat']);
    cf_path = oo_.endo_simul;

    % Variables
    idx_k = find(strcmp(names,'k'));
    idx_lambda = find(strcmp(names,'lambda'));
    idx_r = find(strcmp(names,'r'));
    k_base = base_path(idx_k,:);
    k_cf = cf_path(idx_k,:);
    lambda_base = base_path(idx_lambda,:);
    lambda_cf = cf_path(idx_lambda,:);
    r_base = base_path(idx_r,:);
    r_cf = cf_path(idx_r,:);

    % Percentage change
    k_change = (k_cf-k_base)./k_base;
    lambda_change = (lambda_cf-lambda_base)./lambda_base;
    r_change = (r_cf-r_base)./r_base;

    % Year
    nperiod=size(k_base,2);
    year=(2014:2014+nperiod-1)';
    temp = table(...
        year,...
        repmat(exp,T+1,1),...
        k_change',...
        lambda_change',...
        r_change',...
        'VariableNames',...
        {'year',...
        'experiment',...
        'k_change',...
        'lambda_change',...
        'r_change'});
    output=[output;temp];


end


writetable(output,...
    'policy_transition_results.csv');
save('policy_transition_results.mat','output');
disp('Finished policy transition simulation')
