%% POLICY SWEEPS
%
% Long-run fiscal policy effects
% Gertler (1999) OLG model
%
% Calculate:
%
% (Counterfactual SS - Baseline SS)
% --------------------------------
%        Baseline SS
%
% Variables:
% k, lambda, r
%


clear;
clc;



% Load initial state
data = readtable('initial_states.csv');
state = data(data.year==2014,:);

% Baseline
g0 = 0.20;
e0 = 0.05;
b0 = 0.60;

baseline = run_steady_state(...
    'gertler_policy_g',...
    g0,...
    e0,...
    b0,...
    state);
k0 = baseline.k;
lambda0 = baseline.lambda;
r0 = baseline.r;


output = table();


% 1. Government spending sweep
g_grid = 0.10:0.1:0.60;

for i = 1:length(g_grid)

    g = g_grid(i);
    cf = run_steady_state(...
        'gertler_policy_g',...
        g,...
        e0,...
        b0,...
        state);
    temp = table(...
        g,...
        "Government_Spending",...
        (cf.k-k0)/k0,...
        (cf.lambda-lambda0)/lambda0,...
        (cf.r-r0)/r0,...
        'VariableNames',...
        {'PolicyValue',...
        'PolicyType',...
        'k_change',...
        'lambda_change',...
        'r_change'});
    temp.PolicyType = repmat("Government_Spending",height(temp),1);
    output=[output;temp];
end


% 2. Social security sweep
e_grid = 0.01:0.01:0.07;

for i = 1:length(e_grid)

    e=e_grid(i);
    cf = run_steady_state(...
        'gertler_policy_e',...
        g0,...
        e,...
        b0,...
        state);
    temp=table(...
        e,...
        "Social Security",...
        (cf.k-k0)/k0,...
        (cf.lambda-lambda0)/lambda0,...
        (cf.r-r0)/r0,...
        'VariableNames',...
        {'PolicyValue',...
        'PolicyType',...
        'k_change',...
        'lambda_change',...
        'r_change'});
    temp.PolicyType = repmat("Social_Security",height(temp),1);
    output=[output;temp];

end


% 3. Debt target sweep
b_grid = 0.40:0.05:1.00;

for i = 1:length(b_grid)

    b=b_grid(i);
    cf = run_steady_state(...
        'gertler_policy_b',...
        g0,...
        e0,...
        b,...
        state);
    temp=table(...
        b,...
        "Governmet Debt",...
        (cf.k-k0)/k0,...
        (cf.lambda-lambda0)/lambda0,...
        (cf.r-r0)/r0,...
        'VariableNames',...
        {'PolicyValue',...
        'PolicyType',...
        'k_change',...
        'lambda_change',...
        'r_change'});
    temp.PolicyType = repmat("Debt_Target",height(temp),1);
    output=[output;temp];

end


% Save
writetable(output,'policy_sweep_results.csv');
save('policy_sweep_results.mat','output');
disp('Policy sweep finished')

