%% recursive_forecasts.m
%
% Author: Yujia Ming
% Date: Sept, 2026
% 
% This file provides the code for recursive forecasting for Smets & Wouters (2007)
% DSGE model.
%
% Inputs:
%   `usmodel.mod`
%
% Outputs:
%   recursive_forecast_dsge.csv


clear;
clc;

%-------------------------------------------------------------------------
%% 1. Preparation

% Setting

modfile = 'usmodel.mod'; % dynare model

H = 16; % forecast horizons (quarter)                 

first_origin = 40; % firstly use observations 1:40 to estimate
last_origin = 229; % lastly use observations 1:229 to estimate
n_origins = last_origin - first_origin + 1;

nvar = 7; % number of observables
forecast_dsge = NaN(n_origins, H, nvar);
forecast_origin = (first_origin:last_origin)';


% Modify training data for each iteration in dynare file
% by replacing the original command with a version containing nobs=@{NOBS}

fid = fopen(modfile, 'r'); % read the dynare file
if fid == -1
    error('Cannot open %s', modfile);
end
modtext = fread(fid, '*char')';
fclose(fid);

% locate the start
est_start = strfind(modtext, 'estimation(');
if isempty(est_start)
    error('Cannot find estimation(...) in %s', modfile);
end
est_start = est_start(1);

% locate the end
est_end = strfind(modtext(est_start:end), ';');
if isempty(est_end)
    error('Cannot find the end of estimation(...)');
end
est_end = est_start + est_end(1) - 1;

% extract original estimation command
original_estimation = modtext(est_start:est_end);
disp('Original estimation command:');
disp(original_estimation);


%-------------------------------------------------------------------------
%% 2. Recursive Estimation and Forecasts

% Do not display figures generated by Dynare
set(0, 'DefaultFigureVisible', 'off');

for i = 1:n_origins

    nobs_current = forecast_origin(i);

    fprintf('\n');
    fprintf('=============================================\n');
    fprintf('Forecast origin: %d\n', nobs_current);
    fprintf('Estimation sample: 1:%d\n', nobs_current);
    fprintf('Forecast horizon: %d quarters\n', H);
    fprintf('=============================================\n');


    %% 2.1 Construct new estimation command

    new_estimation = original_estimation;

    % Check whether nobs already exists
    if contains(new_estimation, 'nobs=')

        % Replace existing nobs
        new_estimation = regexprep( ...
            new_estimation, ...
            'nobs\s*=\s*\d+', ...
            sprintf('nobs=%d', nobs_current));

    else

        % Insert nobs after estimation(
        new_estimation = strrep( ...
            new_estimation, ...
            'estimation(', ...
            sprintf('estimation(nobs=%d, ', nobs_current));

    end

    % add forecast option
    new_estimation = strrep( ...
        new_estimation, ...
        ') dy dc dinve labobs pinfobs dw robs;', ...
        sprintf(', forecast=%d) dy dc dinve labobs pinfobs dw robs;', H));


    %% 2.2 Create temporary .mod file

    tempmod = sprintf('usmodel_recursive_%d.mod', nobs_current);

    temptext = modtext;

    % Replace estimation command
    temptext = [ ...
        temptext(1:est_start-1), ...
        new_estimation, ...
        temptext(est_end+1:end) ...
        ];


    % Adjustment: We do NOT want shock_decomposition during every loop.
    temptext = strrep( ...
        temptext, ...
        'shock_decomposition y;', ...
        '% shock_decomposition y;');


    %% 2.3 Write temporary .mod file

    fid = fopen(tempmod, 'w');

    if fid == -1
        error('Cannot create %s', tempmod);
    end

    fwrite(fid, temptext);
    fclose(fid);


    %% 2.4 Run Dynare

    try
        dynare(tempmod, 'noclearall');

    catch ME
        fprintf('\nDynare failed at forecast origin %d.\n', ...
                nobs_current);
        fprintf('%s\n', ME.message);
        rethrow(ME);

    end


    %% 2.5 Extract forecast means

    forecast_dsge(i,:,1) = oo_.forecast.Mean.dy(1:H);

    forecast_dsge(i,:,2) = oo_.forecast.Mean.dc(1:H);

    forecast_dsge(i,:,3) = oo_.forecast.Mean.dinve(1:H);

    forecast_dsge(i,:,4) = oo_.forecast.Mean.labobs(1:H);

    forecast_dsge(i,:,5) = oo_.forecast.Mean.pinfobs(1:H);

    forecast_dsge(i,:,6) = oo_.forecast.Mean.dw(1:H);

    forecast_dsge(i,:,7) = oo_.forecast.Mean.robs(1:H);


    %% 2.6 Display forecasts (optional)

    fprintf('\nDSGE forecasts:\n');

    fprintf('dy:     ');
    fprintf('%10.4f ', forecast_dsge(i,:,1));
    fprintf('\n');

    fprintf('dc:     ');
    fprintf('%10.4f ', forecast_dsge(i,:,2));
    fprintf('\n');

    fprintf('dinve:  ');
    fprintf('%10.4f ', forecast_dsge(i,:,3));
    fprintf('\n');

    fprintf('labobs: ');
    fprintf('%10.4f ', forecast_dsge(i,:,4));
    fprintf('\n');

    fprintf('pinfobs:');
    fprintf('%10.4f ', forecast_dsge(i,:,5));
    fprintf('\n');

    fprintf('dw:     ');
    fprintf('%10.4f ', forecast_dsge(i,:,6));
    fprintf('\n');

    fprintf('robs:   ');
    fprintf('%10.4f ', forecast_dsge(i,:,7));
    fprintf('\n');


end

% Restore MATLAB figure visibility
set(0, 'DefaultFigureVisible', 'on');


% ------------------------------------------------------------------------
%% 3. Save forecasts

save('recursive_forecast_dsge.mat', ...
     'forecast_dsge', ...
     'forecast_origin', ...
     'H');


% save as CSV, as more convenient to calculate RMSE
% Create a table containing forecast origin,
% horizon and variables.

result = [];

for i = 1:n_origins

    for h = 1:H

        forecast_values = squeeze(forecast_dsge(i,h,:));
        forecast_values = forecast_values(:)'; % a row vecor

        row = [ forecast_origin(i), h, forecast_values ];
        result = [result; row];

    end

end


result_table = array2table( ...
    result, ...
    'VariableNames', { ...
    'forecast_origin', ...
    'horizon', ...
    'Output growth rate', ...
    'Consumption growth rate', ...
    'Investment growth rate', ...
    'log Hours worked', ...
    'Inflation', ...
    'Wage growth rate', ...
    'Federal funds rate'});


writetable( result_table, 'recursive_forecast_dsge.csv');


fprintf('\n');
fprintf('=============================================\n');
fprintf('Recursive forecasting finished.\n');
fprintf('Results saved to:\n');
fprintf('  recursive_forecast_dsge.mat\n');
fprintf('  recursive_forecast_dsge.csv\n');
fprintf('=============================================\n');